$(document).ready(function(){
    $("#image1").click(function(){
        $("#image1").hide();
        $("#design-def").show();
    })
    $("#design-def").click(function(){
        $("#design-def").hide();
        $("#image1").show();
    })
});
$(document).ready(function(){
    $("#image2").click(function(){
        $("#image2").hide();
        $("#develop-def").show();
    })
    $("#develop-def").click(function(){
        $("#develop-def").hide();
        $("#image2").show();
    })
});
$(document).ready(function(){
    $("#image3").click(function(){
        $("#image3").hide();
        $("#product-def").show();
    })
    $("#product-def").click(function(){
        $("#product-def").hide();
        $("#image3").show();
    })
});
$(document).ready(function(){
    $("#porfolio1").hover(function(){
        $(".port1").toggle();
    })
})
$(document).ready(function(){
    $("#porfolio2").hover(function(){
        $(".port2").toggle();
    })
})
$(document).ready(function(){
    $("#porfolio3").hover(function(){
        $(".port3").toggle();
    })
})
$(document).ready(function(){
    $("#porfolio4").hover(function(){
        $(".port4").toggle();
    })
})
$(document).ready(function(){
    $("#porfolio5").hover(function(){
        $(".port5").toggle();
    })
})
$(document).ready(function(){
    $("#porfolio6").hover(function(){
        $(".port6").toggle();
    })
})
$(document).ready(function(){
    $("#porfolio7").hover(function(){
        $(".port7").toggle();
    })
})
$(document).ready(function(){
    $("#porfolio8").hover(function(){
        $(".port8").toggle();
    })
})
